### ISSUE TITLE
Schema parse error

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/pyecospold#35]
On a fresh Windows install of pyecospold, one of my colleagues got this error:

```powershell
Traceback (most recent call last):
 File "C:\Python\Mattia\Mattia\property update\untitled0.py", line 14, in <module>

 datasets = pyecospold.parse_directory_v2(dirpath)
  File "C:\Users\Mattia\.conda\envs\ei_tools\lib\site-packages\pyecospold\core.py", line 255, in parse_directory_v2

 return parse_directory(
  File "C:\Users\Mattia\.conda\envs\ei_tools\lib\site-packages\pyecospold\core.py", line 285, in parse_directory

 return [
  File "C:\Users\Mattia\.conda\envs\ei_tools\lib\site-packages\pyecospold\core.py", line 288, in <listcomp>

 parse_file(
  File "C:\Users\Mattia\.conda\envs\ei_tools\lib\site-packages\pyecospold\core.py", line 172, in parse_file

 schema = etree.XMLSchema(file=schema_path)
  File "src\lxml\xmlschema.pxi", line 89, in lxml.etree.XMLSchema.__init__

XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}import': Failed to parse the XML resource 'file:/C:/Users/Mattia/.conda/envs/ei_tools/Lib/site-packages/pyecospold/schemas/v2/XmlNamespace.xsd'., line 21
```

Line 21 is `http://www.rfc-editor.org/rfc/bcp/bcp47.txt</a> and the IANA language subtag registry at <a
`

@sami-m-g I have no clue if this a Windows-specific error or not. Splitting up the `<a>` tag over two lines should be OK? Maybe there is some errors from the encoding of whitespace?

**Comment by sami-m-g** [comment]
@cmutel can you provide the used XML file for local replication of the error?
